Fix dyntest and rename it to dyntest-unit to match the test-unit rename
Docker-DCO-1.1-Signed-off-by: Andrew Page <admwiggin@gmail.com> (github: tianon)

diff --git a/hack/make/dyntest-unit b/hack/make/dyntest-unit
--- a/hack/make/dyntest-unit
+++ b/hack/make/dyntest-unit
@@ -5,7 +5,7 @@ DEST=$1
 INIT=$DEST/../dynbinary/dockerinit-$VERSION
 
 if [ ! -x "$INIT" ]; then
-	echo >&2 'error: dynbinary must be run before dyntest'
+	echo >&2 'error: dynbinary must be run before dyntest-unit'
 	false
 fi
 
@@ -14,5 +14,5 @@ fi
 	export LDFLAGS_STATIC_DOCKER="
 		-X github.com/dotcloud/docker/dockerversion.INITSHA1 \"$DOCKER_INITSHA1\"
 	"
-	source "$(dirname "$BASH_SOURCE")/test"
+	source "$(dirname "$BASH_SOURCE")/test-unit"
 )
