Cleanup test output, and binaries.
Signed-off-by: Daniel Nephin <dnephin@docker.com>

diff --git a/hack/make/test-integration b/hack/make/test-integration
--- a/hack/make/test-integration
+++ b/hack/make/test-integration
@@ -4,28 +4,19 @@ set -e
 source "${MAKEDIR}/.go-autogen"
 source hack/make/.integration-test-helpers
 
-# subshell so that we can export PATH without breaking other things
 (
-    build_test_suite_binaries
-
+	build_test_suite_binaries
 	bundle .integration-daemon-start
-
 	bundle .integration-daemon-setup
 
-	bundle_test_integration
+	local testexit=0
+	( repeat run_test_integration ) || testexit=$?
 
+	# Always run cleanup, even if the subshell fails
 	bundle .integration-daemon-stop
+	cleanup_test_suite_binaries
+	error_on_leaked_containerd_shims
 
-	if [ "$(go env GOOS)" != 'windows' ]
-	then
-		leftovers=$(ps -ax -o pid,cmd | awk '$2 == "docker-containerd-shim" && $4 ~ /.*\/bundles\/.*\/test-integration/ { print $1 }')
-		if [ -n "$leftovers" ]
-		then
-			ps aux
-			kill -9 $leftovers 2> /dev/null
-			echo "!!!! WARNING you have left over shim(s), Cleanup your test !!!!"
-			exit 1
-		fi
-	fi
+	exit $testexit
 
 ) 2>&1 | tee -a "$DEST/test.log"
