hack: reduce time of integration tests by dividing tests to 3 separate daemons
Signed-off-by: Tibor Vass <tibor@docker.com>

diff --git a/hack/make/test-integration b/hack/make/test-integration
--- a/hack/make/test-integration
+++ b/hack/make/test-integration
@@ -4,24 +4,25 @@ set -e -o pipefail
 source hack/make/.integration-test-helpers
 
 if [ ! -z "${TEST_SKIP_INTEGRATION}" ] && [ ! -z "${TEST_SKIP_INTEGRATION_CLI}" ]; then
-	echo integration and integraiton-cli skipped according to env vars
+	echo integration and integration-cli skipped according to env vars
 	exit 0
 fi
 
-
+export DEST="${DEST}${TEST_INTEGRATION_DEST}"
+mkdir -p "$DEST"
 (
-	build_test_suite_binaries
-	bundle .integration-daemon-start
-	bundle .integration-daemon-setup
+       build_test_suite_binaries
+       bundle .integration-daemon-start
+       bundle .integration-daemon-setup
 
-	testexit=0
-	( repeat run_test_integration ) || testexit=$?
+       testexit=0
+       ( repeat run_test_integration ) || testexit=$?
 
-	# Always run cleanup, even if the subshell fails
-	bundle .integration-daemon-stop
-	cleanup_test_suite_binaries
-	error_on_leaked_containerd_shims
+       # Always run cleanup, even if the subshell fails
+       bundle .integration-daemon-stop
+       cleanup_test_suite_binaries
+       error_on_leaked_containerd_shims
 
-	exit ${testexit}
+       exit ${testexit}
 
 ) 2>&1 | tee -a "$DEST/test.log"
